# -*- coding: utf-8 -*-
"""
Created on Mon Mar 28 10:07:08 2022

Some useful functions

@author: CC
"""
import numpy as np
import random

def read_heads_dat(NC, NR, filename, time_step_num):
    # Reads out heads data from "heads.dat" file generated by modflow-2005

    headers = 11
    data = np.fromfile(filename,dtype=np.float32)
    i = 1
    b = np.zeros(shape = (NC * NR + headers, time_step_num))
    c = np.zeros(shape = (NC * NR, time_step_num))
    c1 = np.zeros(shape = (NC, NR, time_step_num))

    while i <= time_step_num:
        # split the whole matrix to seperated matrix with one matrix for each
        # time step
        b[:, i - 1] = data[int(data.size / time_step_num * (i - 1)) : int(data.size / time_step_num * i)]
    
        i = i + 1
    
    for i in range(time_step_num):
        c[:, i] = b[(headers):b.shape[0], i]
    
    for i in range(time_step_num):
        c1[:,:,i] = c[:, i].reshape((NC, NR))
    
    heads = c1
    return heads
def gen_rand_pos(NC, NR, rand_num):
    # generate random positions
    # return the coordinates of the position as (row, col) in the matrix

    rand_pos = np.zeros((rand_num, 2),dtype = int)
    rand_index = random.sample(range(0, NC * NR), rand_num)
    rand_index.sort() 
    for i in range(len(rand_index)):
        x = rand_index[i] // NC
        y = rand_index[i] % NC
        rand_pos[i, 0] = x
        rand_pos[i, 1] = y
    return rand_pos