# -*- coding: utf-8 -*-
"""
Created on  2024/4/2


@author: wangsyu
"""
import pandas as pd
import os
import re
import numpy as np
import matplotlib.pyplot as plt
def read_heads_dat(NC, NR, filename, time_step_num):
    # Reads out heads data from "heads.dat" file generated by modflow-2005

    headers = 11
    data = np.fromfile(filename,dtype=np.float32)
    i = 1
    b = np.zeros(shape = (NC * NR + headers, time_step_num))
    c = np.zeros(shape = (NC * NR, time_step_num))
    c1 = np.zeros(shape = (NC, NR, time_step_num))

    while i <= time_step_num:
        # split the whole matrix to seperated matrix with one matrix for each
        # time step
        b[:, i - 1] = data[int(data.size / time_step_num * (i - 1)) : int(data.size / time_step_num * i)]
    
        i = i + 1
    
    for i in range(time_step_num):
        c[:, i] = b[(headers):b.shape[0], i]
    
    for i in range(time_step_num):
        c1[:,:,i] = c[:, i].reshape((NC, NR))
    
    heads = c1
    return heads

def get_points(points_r_c):
    points = []
    for value in points_r_c.values:
        points.append(value)
    points = np.array(points).reshape(-1, 2)
    return points

#用于处理行列坐标减一，和head.dat文件对应
def contains_chinese(text):
    return any(re.search("[\u4e00-\u9fff]",str(item)) for item in text)
# 读取Excel文件
def pre_data(input_file_path, output_file_suffix,skiprows,header,usecols):
    df = pd.read_excel(input_file_path,skiprows = skiprows,header = header,usecols = usecols)
    #删除包含汉字的行
    df = df[~df.apply(contains_chinese, axis = 1)]
    # 将前两列的每一列数据都减去1   
    # for i in range(2):
    #     df.iloc[:, i] = df.iloc[:, i] - 1
    df = df.map(lambda x: int(np.floor(x - 1)) if isinstance(x, (int, float)) else x)   #接受一个匿名x，如果x是int或float类型，则执行int(np.floor(x - 1)) ，else 只是返回x
     
    # 只对第一列和第二列进行处理
    # for i in range(2):
    #     df.iloc[:, i] = df.iloc[:, i].apply(lambda x: int(np.floor(x - 1)) if isinstance(x, (int, float)) else x)
           
    R_C = df  #读取减一后的数值
    #分割原文件路径和扩展名
    file_base, file_extension = os.path.splitext(input_file_path)
    #在原文件命名上添加“减一” output_file_suffix值要传递的减一
    output_file_path = f"{file_base}{output_file_suffix}{file_extension}"
    
    # 保存修改后的数据为新的Excel文件
    df.to_excel(output_file_path, index=False)
    
    # if __name__ == '__main__':
    #     print(f"处理完成，保存为 {output_file_path}")
        
    return R_C

zuobiao_fn = '/home/cc/CCFs/Wangf/UNPINN/read_obs/output.xlsx'
suffix = '_minus_1'  # 减一
zuobiao_r_c = pre_data(zuobiao_fn, suffix, skiprows=1, header=None, usecols=None)
zuobiao_50_50 =  get_points(zuobiao_r_c)


NC = 51
NR = 51
time_step_num = 50
UA_D_head_fn = '/home/cc/CCFs/Wangf/UNPINN/modflow/case_study_12/heads.dat'
UA_D_heads = read_heads_dat(NC, NR, UA_D_head_fn, time_step_num)
print(np.max(UA_D_heads))
print(np.min(UA_D_heads))
# 保存结果的路径
save_path = '/home/cc/CCFs/Wangf/UNPINN/read_obs/savefig_UA_N3d/'
os.makedirs(save_path, exist_ok=True)  # 如果路径不存在，则创建

# for t in range(UA_D_heads.shape[2]):
#     data = UA_D_heads[:,:,t]
#         # 绘制热力图
#     plt.figure(figsize=(8, 6))
#     plt.imshow(data, cmap='jet', interpolation='nearest', vmin=4, vmax=7)  # 设置颜色范围和颜色条
#     plt.colorbar(label="Value")  # 添加颜色条
#     plt.title(f"Heatmap at Time Step {t+1}")  # 标题标注当前时间步
#     plt.xlabel("Column")
#     plt.ylabel("Row")
#     plt.tight_layout()
#     # 保存热力图
#     plt.savefig(f"{save_path}heatmap_timestep_{t+1}.png")
#     plt.close()  # 关闭当前图像以释放内存


def main():


    # x 和 y 网格坐标
    x = np.linspace(0, 50, UA_D_heads.shape[0])  # x 坐标
    y = np.linspace(0, 50, UA_D_heads.shape[1])  # y 坐标
    X, Y = np.meshgrid(x, y)  # 创建网格坐标

    # 遍历时间步
    for t in range(UA_D_heads.shape[2]):  # UA_D_heads.shape[2] 是时间步的数量
        grid_data = UA_D_heads[:, :, t]  # 提取当前时间步的 51x51 网格数据

        # 创建三维图
        fig = plt.figure(figsize=(10, 8))
        ax = fig.add_subplot(111, projection='3d')

        # 绘制三维表面图
        surf = ax.plot_surface(X, Y, grid_data, cmap='jet', vmin=1, vmax=10, edgecolor='none')

        # 设置坐标轴标签
        ax.set_xlabel(r'$x/m$', fontsize=15, labelpad=10, fontweight='bold')
        ax.set_ylabel(r'$y/m$', fontsize=15, labelpad=10, fontweight='bold')
        ax.set_zlabel(r'$H/m$', fontsize=15, labelpad=10, fontweight='bold')

        # 设置轴刻度字体大小
        ax.tick_params(axis='both', which='major', labelsize=12)

        # 添加颜色条
        cbar = fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10)
        cbar.ax.tick_params(labelsize=12)  # 设置颜色条刻度字体大小
        cbar.set_label(r'$H/m$', fontsize=15, fontweight='bold')

        # 设置图标题
        ax.set_title(f"3D Surface at Timestep {t + 1}", fontsize=15, fontweight='bold')

        # 保存图像
        plt.savefig(os.path.join(save_path, f'3D_Surface_Timestep_{t + 1}.png'))
        plt.close()  # 关闭当前绘图，释放内存

if __name__ == "__main__":
    main()
